server:
  port: 8012
  
logging:
  level:
    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
      springframework:
        web: INFO
    root: WARN
spring:
  application:
    name: burry-weather
  banner:
    location: classpath:/static/bannername.txt
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
#        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 90000
        loggerLevel: basic
hystrix:
  shareSecurityContext: false
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: -1
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        forceClosed: true
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 10000


