[template]
src = "credentials.conf.tmpl"
dest = "/app/credentials/credentials.properties"
keys = [
    "/spring/datasource/username",
    "/spring/datasource/password",
    "/spring/rabbitmq/username",
    "/spring/rabbitmq/password"
]